### ISSUE TITLE
ingress controller vs ingress resource

### ISSUE THREAD

**Issue by ram-argus** [kelseyhightower/ingress-with-static-ip#1]
I think you may be using the term [ingress-controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers) and mean [ingress resource](http://kubernetes.io/docs/user-guide/ingress/#the-ingress-resource); you seem to be creating an Ingress resource. the ingress-controller in GKE, , GLBC/l7/gce ingress-controller, runs hidden on the master-node, right?

on different note:
while this demo is interesting, it has a rather limited use-case. looking at the slack channel, I think people are VERY confused about:
- how to setup ingress controller in prod with several controllers for HA (daemonset vs deployment of 3 pros/cons)
- how to expose the ingress-controller to the outside (using a service with LB over the controller pods, adding DNS entry to sub-domain)
- adding tls to the ingress (kube-lego, your kube-cert-manager, etc)
- difference between l4 & l7 ingress controllers, how it works in GCE and in AWS. and what can I do in bare-metal?

In general, I think the integration with the cloud-provider is missing proper documentation, as k8s docs try to remain generic (which is fine). that's where the dev-advocate super-hero comes in to save the day, right?  ;)

**Comment by kelseyhightower** [comment]
@ram-argus I was asked about 1 simple use case and that's what I wrote up. I'm not trying to boil the ocean, just address the specific use-case, I'm not a hero, just some one being helpful.

I tend to focus on solving people problems and sometimes that 1 really specific use case like this one. Some people find it useful, that works for me.

The feedback regarding ingress-controller vs ingress resource is correct and I'll update the guide. Thanks for the feedback.
